- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/BPC-11223
> feature(eti): creation product

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/eti/product_statuses_spec.rb
- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
- lib/pages/company_site/eti_page.rb
- lib/pages/company_site/mini_eti_page.rb
https://jira.railsc.ru/browse/BPC-11225
> feature(eti): product status tests

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
- lib/pages/company_site/eti_page.rb
- lib/pages/company_site/mini_eti_page.rb
https://jira.railsc.ru/browse/AT-33
> feature(eti): product copying tests

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/eti/product_statuses_spec.rb
- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
https://jira.railsc.ru/browse/AT-85
> feature: open new browser for every specs

- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-76
@rezerbit @Copperface @EvgeniaKruglova
> feature(eti): add lost locators

- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-25
> fix(minieti): image locator

- lib/apress/selenium_eti/spec/company_site/eti/product_groups_spec.rb
- lib/pages/company_site/eti_page.rb
По техническим причинам создала повторный ПР
https://jira.railsc.ru/browse/AT-26
> feature(eti): add groups test

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-79
> fix(eti): delete product after copy

- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
https://jira.railsc.ru/browse/AT-105
> fix: add new companies fot eti, minieti & offers_product

- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
https://jira.railsc.ru/browse/AT-109
> fix: add skips for knife

- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
@ovsyanik-ka
@nestrik
@rezerbit
> regexp instead string

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-167
> Fix: improve tests stability and some fixes

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-175
> fix: hide support contacts and fix rubric locator

- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-215
> fix: minieti_spec

- lib/apress/selenium_eti/spec/company_site/eti/product_statuses_spec.rb
https://jira.railsc.ru/browse/AT-242
> fix: close support contacts panel

- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-254
> fix: after orders-cosmos and august-2

- lib/apress/selenium_eti/spec/company_site/minieti_spec.rb
https://jira.railsc.ru/browse/AT-281
> fix(selenium) уберем скипы

- lib/apress/selenium_eti/version.rb
Не выпустилась версия. Нужно убрать мой коммит.
> revert gem version

- lib/apress/selenium_eti/version.rb
> Release 0.6.6

- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-326
> fix: after release

- lib/apress/selenium_eti/spec/company_site/eti/product_creation_spec.rb
- lib/apress/selenium_eti/spec/company_site/eti/product_price_spec.rb
- lib/pages/company_site/eti_page.rb
https://jira.railsc.ru/browse/AT-557
Озеленил (поправил) падающие тесты в геме ЕТИ:
1. обновил локаторы
2. добавил в ожидаемый результат определение проекта через локаторы и соответствующие проверки проекту  (с помощью условий if, elsif, else)
3. закомментировал шаги, которые приводят к [багу](https://jira.railsc.ru/browse/GOODS-3568)
В дальнейшем п.2 надо будет улучшить до использования метода
> fix(selenium): fix specs eti

- README.md
https://jira.railsc.ru/browse/AT-582
Актуализировал README под текущие реалии: как работать с тестами в текущем геме, как настроить локально прогон тестов гема в проекте
Повышать версию гема не буду, думаю лучше это сделать когда будут более существенные изменения в геме
> fix(README.md): update README

- lib/apress/selenium_products/version.rb
- lib/pages/company_site/eti/popups/images_upload_popup.rb
https://jira.railsc.ru/browse/AT-636
> fix(selenium): fix mini-eti spec: images_upload_popup [skip ci]

- lib/pages/company_site/eti/action_panel.rb
https://jira.railsc.ru/browse/AT-642
> fix: change some methods

- lib/apress/selenium_products/version.rb
- lib/pages/company_site/product_creation_page.rb
https://jira.railsc.ru/browse/AT-679
- Добавил ожидание для получения портальных характеристик
> fix(selenium): add wait for portal traits values [skip ci]

- lib/apress/selenium_products/spec/company_site/kirby/import/import_yml_policy_spec.rb
- lib/apress/selenium_products/version.rb
- lib/pages/company_site/import_yml_page.rb
- Поправил падающие/скипнутые тесты по странице импорта yml, после редизайна страницы и перенес их в гем из проекта Blizko.
- https://jira.railsc.ru/browse/AT-639
> feat(selenium): add kirby import yml spec from the blizko

- lib/apress/selenium_products/spec/company_site/tigr/tigr_spec.rb
- lib/apress/selenium_products/version.rb
- lib/pages/company_site/tigr/tigr_page.rb
- Вынесла [tigr_spec](https://github.com/abak-press/blizko/blob/master/selenium/spec/tigr_spec.rb) из проекта Blizko в гем
> feat(selenium): add tigr_spec from blizko
